apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ping-pong-service

resources:
  - ../../base

components:
  - ../../components/receiver
  - ../../components/sender

generatorOptions:
 disableNameSuffixHash: true

configMapGenerator:
- name: certificatestores
  files:
    - certificates/client.p12
    - certificates/serverks.jks