apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-service
spec:
  selector:
    matchLabels:
      app: ping-pong-service
  template:
    metadata:
      labels:
        app: ping-pong-service
    spec:
      containers:
        - image: ghcr.io/deb4sh/ldap-homelab:sha-1033f81
          name: sender
          envFrom:
            - configMapRef:
                name: configuration-sender
          volumeMounts:
            - name: certificates
              mountPath: /tmp/certs
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "150m"