apiVersion: v1
kind: ConfigMap
metadata:
  name: configuration-metrics
data:
  rabbitmq.username: "YOUR_AWESOME_USERNAME"
  rabbitmq.password: "YOUR_AWESOME_PASSWORD"
  rabbitmq.host: "YOUR_AWESOME_BROKER_URL"
  rabbitmq.port: "5671"
  rabbitmq.virtualhost: "/"
  rabbitmq.sender.queue: "ping-pong-sender"
  rabbitmq.receiver.queue: "ping-pong-receiver"
  client.mode: "metrics"
  rabbitmq.metrics.envname: "" # nametemplate: rabbitmq_sender_%s_timestamp , rabbitmq_receiver_%s_timestamp
  #client cert specific env vars
  rabbitmq.useclientcert: "true"
  rabbitmq.clientkeystorepassphase: "ping-pong"
  rabbitmq.clientkeystorepath: "/tmp/certs/client.p12"
  rabbitmq.serverkeystorepassphase: "ping-pong"
  rabbitmq.serverkeystorepath: "/tmp/certs/serverks.jks"
