name: Docker-Build

on:
  push:
    tags:
      - "*"

# permissions are needed if pushing to ghcr.io
permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta_build
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/hamburg-port-authority/rppc
          # Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=tag
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_build.outputs.tags }}
          labels: ${{ steps.meta_build.outputs.labels }}

      - name: Install cosign
        uses: sigstore/cosign-installer@main

      - name: Cosign check install!
        run: cosign version 

      - name: Extract First Tag
        id: extract_tag
        run: echo "::set-output name=first_tag::$(echo '${{ steps.meta_build.outputs.tags }}' | awk '{print $1}')"
      - name: Debug First Tag
        run: echo "First Tag ${{ steps.extract_tag.outputs.first_tag }}"

      - name: Sign the container image
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: cosign sign --yes ${{ steps.extract_tag.outputs.first_tag }}

      - name: Verify the images
        run: |
          cosign verify ghcr.io/Hamburg-Port-Authority/rppc \
            --certificate-identity https://github.com/Hamburg-Port-Authority/rppc/.github/workflows/main.yml@refs/heads/main \
            --certificate-oidc-issuer https://token.actions.githubusercontent.com | jq       
